export interface Product {
  id: string;
  name: string;
  slug: string;
  url: string;
  image?: string;
  category: string;
}

export const categories = {
  hits: {
    name: 'Хиты',
    slug: 'hits',
    icon: '⭐',
  },
  'starter-kits': {
    name: 'Стартовые наборы',
    slug: 'starter-kits',
    icon: '📦',
  },
  'new-products': {
    name: 'Новинки',
    slug: 'new-products',
    icon: '✨',
  },
  'brain-care': {
    name: 'Забота о мозге',
    slug: 'brain-care',
    icon: '🧠',
  },
  'health-supplement': {
    name: 'БАД',
    slug: 'health-supplement',
    icon: '💊',
  },
  slimming: {
    name: 'Похудение',
    slug: 'slimming',
    icon: '⚖️',
  },
  'healthy-eating': {
    name: 'Здоровое Питание',
    slug: 'healthy-eating',
    icon: '🥗',
  },
  drinks: {
    name: 'Напитки',
    slug: 'drinks',
    icon: '☕',
  },
  'beauty-and-care': {
    name: 'Красота и уход',
    slug: 'beauty-and-care',
    icon: '💄',
  },
  'gift-ideas': {
    name: 'Идеи подарков',
    slug: 'gift-ideas',
    icon: '🎁',
  },
  home: {
    name: 'Дом',
    slug: 'home',
    icon: '🏠',
  },
  accessories: {
    name: 'Аксессуары',
    slug: 'accessories',
    icon: '👕',
  },
  'activation-kits': {
    name: 'Наборы для активации',
    slug: 'activation-kits',
    icon: '🎯',
  },
  'expert-cosmetics': {
    name: 'Expert Cosmetics',
    slug: 'expert-cosmetics',
    icon: '✨',
  },
  all: {
    name: 'Все продукты',
    slug: 'shop',
    icon: '🛍️',
  },
};

export const products: Record<string, Product[]> = {
  hits: [
    { id: '1', name: 'BRAINSTORM (морошка)', slug: 'brainstorm-cloudberry', url: 'https://ewaproduct.com/product/brainstorm-cloudberry', category: 'hits' },
    { id: '2', name: 'BRAINSTORM (вишня)', slug: 'brainstorm-so-vkusom-vishni', url: 'https://ewaproduct.com/product/brainstorm-so-vkusom-vishni', category: 'hits' },
    { id: '3', name: 'IQ BOOSTER', slug: 'iq-booster', url: 'https://ewaproduct.com/product/iq-booster', category: 'hits' },
    { id: '4', name: 'TONE', slug: 'tone', url: 'https://ewaproduct.com/product/tone', category: 'hits' },
    { id: '5', name: 'NO STRESS', slug: 'no-stress', url: 'https://ewaproduct.com/product/no-stress', category: 'hits' },
    { id: '6', name: 'FIRE SLIM', slug: 'fire-slim', url: 'https://ewaproduct.com/product/fire-slim', category: 'hits' },
    { id: '7', name: 'DRAINAGE 2.0', slug: 'drainage-20', url: 'https://ewaproduct.com/product/drainage-20', category: 'hits' },
    { id: '8', name: 'PRO SLIM', slug: 'pro-slim', url: 'https://ewaproduct.com/product/pro-slim', category: 'hits' },
    { id: '9', name: 'DETOX EASY', slug: 'detox-easy', url: 'https://ewaproduct.com/product/detox-easy', category: 'hits' },
    { id: '10', name: 'NIGHT COLLAGEN', slug: 'night-collagen', url: 'https://ewaproduct.com/product/night-collagen', category: 'hits' },
    { id: '11', name: 'COLLAGEN HONDROSKIN (цитрус)', slug: 'collagen-hondroskin-so-vkusom-citrusa', url: 'https://ewaproduct.com/product/collagen-hondroskin-so-vkusom-citrusa', category: 'hits' },
    { id: '12', name: 'COLLAGEN HONDROSKIN (клюква-апельсин)', slug: 'collagen-hondroskin', url: 'https://ewaproduct.com/product/collagen-hondroskin', category: 'hits' },
    { id: '13', name: 'FLEX', slug: 'flex', url: 'https://ewaproduct.com/product/flex', category: 'hits' },
    { id: '14', name: 'EWA PROTECT 2.0', slug: 'ewa-protect-20', url: 'https://ewaproduct.com/product/ewa-protect-20', category: 'hits' },
  ],
  'starter-kits': [
    { id: '15', name: 'STARTER PACK 1', slug: 'starter-pack-1', url: 'https://ewaproduct.com/product/starter-pack-1', category: 'starter-kits' },
    { id: '16', name: 'STARTER PACK 2', slug: 'starter-pack-2', url: 'https://ewaproduct.com/product/starter-pack-2', category: 'starter-kits' },
    { id: '17', name: 'STARTER PACK 3', slug: 'starter-pack-3', url: 'https://ewaproduct.com/product/starter-pack-3', category: 'starter-kits' },
    { id: '18', name: 'STARTER PACK 4', slug: 'starter-pack-4', url: 'https://ewaproduct.com/product/starter-pack-4', category: 'starter-kits' },
    { id: '19', name: 'STARTER PACK 5', slug: 'starter-pack-5', url: 'https://ewaproduct.com/product/starter-pack-5', category: 'starter-kits' },
    { id: '20', name: 'STARTER PACK 6', slug: 'starter-pack-6', url: 'https://ewaproduct.com/product/starter-pack-6', category: 'starter-kits' },
    { id: '21', name: 'STARTER PACK 7', slug: 'starter-pack-7', url: 'https://ewaproduct.com/product/starter-pack-7', category: 'starter-kits' },
  ],
  'new-products': [
    { id: '22', name: 'LIFRESH', slug: 'lifresh', url: 'https://ewaproduct.com/product/lifresh', category: 'new-products' },
    { id: '23', name: 'COLLAGEN YOUNG&BEAUTY', slug: 'collagen-young', url: 'https://ewaproduct.com/product/collagen-young', category: 'new-products' },
    { id: '24', name: 'BIG SLIM SET', slug: 'big-set-2-new', url: 'https://ewaproduct.com/product/big-set-2-new', category: 'new-products' },
    { id: '25', name: 'BODYBOX 2.0 TROPICAL MIX', slug: 'bodybox-20-pistachio-tropic', url: 'https://ewaproduct.com/product/bodybox-20-pistachio-tropic', category: 'new-products' },
    { id: '26', name: 'PROTEIN DOUBLE CHOCOLATE', slug: 'protein-double', url: 'https://ewaproduct.com/product/protein-double', category: 'new-products' },
    { id: '27', name: 'PROTEIN NOUGAT', slug: 'protein-noigat', url: 'https://ewaproduct.com/product/protein-noigat', category: 'new-products' },
    { id: '28', name: 'PROTEIN MELON', slug: 'protein-melon', url: 'https://ewaproduct.com/product/protein-melon', category: 'new-products' },
    { id: '29', name: 'ANTI-AGE SET', slug: 'anti-age-box-new', url: 'https://ewaproduct.com/product/anti-age-box-new', category: 'new-products' },
    { id: '30', name: 'ANTI-AGE DAY CREAM', slug: 'anti-age-day-cream', url: 'https://ewaproduct.com/product/anti-age-day-cream', category: 'new-products' },
    { id: '31', name: 'ANTI-AGE NIGHT CREAM', slug: 'anti-age-night-cream', url: 'https://ewaproduct.com/product/anti-age-night-cream', category: 'new-products' },
    { id: '32', name: 'ANTI-AGE MULTI-SERUM', slug: 'anti-age-multi-serum', url: 'https://ewaproduct.com/product/anti-age-multi-serum', category: 'new-products' },
    { id: '33', name: 'ANTI-AGE EYE CREAM', slug: 'anti-age-eye-cream', url: 'https://ewaproduct.com/product/anti-age-eye-cream', category: 'new-products' },
    { id: '34', name: 'SLIM SCRUB «CURRANT BUSH»', slug: 'slim-scrub-brush', url: 'https://ewaproduct.com/product/slim-scrub-brush', category: 'new-products' },
    { id: '35', name: 'DETOX SCRUB «CANDY CARAMEL»', slug: 'detox-scrub-caramel', url: 'https://ewaproduct.com/product/detox-scrub-caramel', category: 'new-products' },
  ],
  'brain-care': [
    { id: '36', name: 'BRAINSTORM (морошка)', slug: 'brainstorm-cloudberry', url: 'https://ewaproduct.com/product/brainstorm-cloudberry', category: 'brain-care' },
    { id: '37', name: 'BRAINSTORM (вишня)', slug: 'brainstorm-so-vkusom-vishni', url: 'https://ewaproduct.com/product/brainstorm-so-vkusom-vishni', category: 'brain-care' },
    { id: '38', name: 'IQ BOOSTER', slug: 'iq-booster', url: 'https://ewaproduct.com/product/iq-booster', category: 'brain-care' },
    { id: '39', name: 'TONE', slug: 'tone', url: 'https://ewaproduct.com/product/tone', category: 'brain-care' },
    { id: '40', name: 'NO STRESS', slug: 'no-stress', url: 'https://ewaproduct.com/product/no-stress', category: 'brain-care' },
    { id: '41', name: 'FOCUS ON ENERGY & RESULT', slug: 'focus-on-energy-result', url: 'https://ewaproduct.com/product/focus-on-energy-result', category: 'brain-care' },
    { id: '42', name: 'FOCUS ON MIND & RELAX', slug: 'focus-on-mind-relax', url: 'https://ewaproduct.com/product/focus-on-mind-relax', category: 'brain-care' },
    { id: '43', name: 'POWER & ENERGY', slug: 'power-energy', url: 'https://ewaproduct.com/product/power-energy', category: 'brain-care' },
  ],
  'health-supplement': [
    { id: '44', name: 'BRAINSTORM (морошка)', slug: 'brainstorm-cloudberry', url: 'https://ewaproduct.com/product/brainstorm-cloudberry', category: 'health-supplement' },
    { id: '45', name: 'BRAINSTORM (вишня)', slug: 'brainstorm-so-vkusom-vishni', url: 'https://ewaproduct.com/product/brainstorm-so-vkusom-vishni', category: 'health-supplement' },
    { id: '46', name: 'IQ BOOSTER', slug: 'iq-booster', url: 'https://ewaproduct.com/product/iq-booster', category: 'health-supplement' },
    { id: '47', name: 'TONE', slug: 'tone', url: 'https://ewaproduct.com/product/tone', category: 'health-supplement' },
    { id: '48', name: 'NO STRESS', slug: 'no-stress', url: 'https://ewaproduct.com/product/no-stress', category: 'health-supplement' },
    { id: '49', name: 'FIRE SLIM', slug: 'fire-slim', url: 'https://ewaproduct.com/product/fire-slim', category: 'health-supplement' },
    { id: '50', name: 'DRAINAGE 2.0', slug: 'drainage-20', url: 'https://ewaproduct.com/product/drainage-20', category: 'health-supplement' },
    { id: '51', name: 'PRO SLIM', slug: 'pro-slim', url: 'https://ewaproduct.com/product/pro-slim', category: 'health-supplement' },
    { id: '52', name: 'DETOX EASY', slug: 'detox-easy', url: 'https://ewaproduct.com/product/detox-easy', category: 'health-supplement' },
    { id: '53', name: 'LIFRESH', slug: 'lifresh', url: 'https://ewaproduct.com/product/lifresh', category: 'health-supplement' },
    { id: '54', name: 'METABIOTIC PROACTIVE FORMULA', slug: 'metabiotic-proactive-formula', url: 'https://ewaproduct.com/product/metabiotic-proactive-formula', category: 'health-supplement' },
    { id: '55', name: 'NIGHT COLLAGEN', slug: 'night-collagen', url: 'https://ewaproduct.com/product/night-collagen', category: 'health-supplement' },
    { id: '56', name: 'COLLAGEN HONDROSKIN (цитрус)', slug: 'collagen-hondroskin-so-vkusom-citrusa', url: 'https://ewaproduct.com/product/collagen-hondroskin-so-vkusom-citrusa', category: 'health-supplement' },
    { id: '57', name: 'COLLAGEN HONDROSKIN (клюква-апельсин)', slug: 'collagen-hondroskin', url: 'https://ewaproduct.com/product/collagen-hondroskin', category: 'health-supplement' },
    { id: '58', name: 'FLEX', slug: 'flex', url: 'https://ewaproduct.com/product/flex', category: 'health-supplement' },
    { id: '59', name: 'FLAME MAN', slug: 'flameman', url: 'https://ewaproduct.com/product/flameman', category: 'health-supplement' },
    { id: '60', name: 'FLAME WOMAN', slug: 'flamewoman', url: 'https://ewaproduct.com/product/flamewoman', category: 'health-supplement' },
    { id: '61', name: 'IMMUNOPUMP', slug: 'immunopump', url: 'https://ewaproduct.com/product/immunopump', category: 'health-supplement' },
    { id: '62', name: 'EWA PROTECT 2.0', slug: 'ewa-protect-20', url: 'https://ewaproduct.com/product/ewa-protect-20', category: 'health-supplement' },
    { id: '63', name: 'IRON', slug: 'iron-60', url: 'https://ewaproduct.com/product/iron-60', category: 'health-supplement' },
    { id: '64', name: 'OMEGA 3 EXTRA', slug: 'omega-3-extra', url: 'https://ewaproduct.com/product/omega-3-extra', category: 'health-supplement' },
    { id: '65', name: 'VITAMIN D3 EXTRA', slug: 'vitamin-d3-extra-weekend-sale', url: 'https://ewaproduct.com/product/vitamin-d3-extra-weekend-sale', category: 'health-supplement' },
    { id: '66', name: 'FOCUS ON ENERGY & RESULT', slug: 'focus-on-energy-result', url: 'https://ewaproduct.com/product/focus-on-energy-result', category: 'health-supplement' },
    { id: '67', name: 'FOCUS ON SLIM & BEAUTY', slug: 'focus-on-slim-beauty', url: 'https://ewaproduct.com/product/focus-on-slim-beauty', category: 'health-supplement' },
    { id: '68', name: 'FOCUS ON MIND & RELAX', slug: 'focus-on-mind-relax', url: 'https://ewaproduct.com/product/focus-on-mind-relax', category: 'health-supplement' },
    { id: '69', name: 'STRENGTH & OPPORTUNITIES', slug: 'strength-opportunities', url: 'https://ewaproduct.com/product/strength-opportunities', category: 'health-supplement' },
    { id: '70', name: 'POWER & ENERGY', slug: 'power-energy', url: 'https://ewaproduct.com/product/power-energy', category: 'health-supplement' },
    { id: '71', name: 'ENERGY & SENSUAL', slug: 'energy-sensual', url: 'https://ewaproduct.com/product/energy-sensual', category: 'health-supplement' },
  ],
  slimming: [
    { id: '72', name: 'FIRE SLIM', slug: 'fire-slim', url: 'https://ewaproduct.com/product/fire-slim', category: 'slimming' },
    { id: '73', name: 'DRAINAGE 2.0', slug: 'drainage-20', url: 'https://ewaproduct.com/product/drainage-20', category: 'slimming' },
    { id: '74', name: 'PRO SLIM', slug: 'pro-slim', url: 'https://ewaproduct.com/product/pro-slim', category: 'slimming' },
    { id: '75', name: 'DETOX EASY', slug: 'detox-easy', url: 'https://ewaproduct.com/product/detox-easy', category: 'slimming' },
    { id: '76', name: 'NIGHT COLLAGEN', slug: 'night-collagen', url: 'https://ewaproduct.com/product/night-collagen', category: 'slimming' },
    { id: '77', name: 'COLLAGEN YOUNG&BEAUTY', slug: 'collagen-young', url: 'https://ewaproduct.com/product/collagen-young', category: 'slimming' },
    { id: '78', name: 'COLLAGEN HONDROSKIN (цитрус)', slug: 'collagen-hondroskin-so-vkusom-citrusa', url: 'https://ewaproduct.com/product/collagen-hondroskin-so-vkusom-citrusa', category: 'slimming' },
    { id: '79', name: 'COLLAGEN HONDROSKIN (клюква-апельсин)', slug: 'collagen-hondroskin', url: 'https://ewaproduct.com/product/collagen-hondroskin', category: 'slimming' },
    { id: '80', name: 'FLEX', slug: 'flex', url: 'https://ewaproduct.com/product/flex', category: 'slimming' },
    { id: '81', name: 'BODYBOX 2.0 TROPICAL MIX', slug: 'bodybox-20-pistachio-tropic', url: 'https://ewaproduct.com/product/bodybox-20-pistachio-tropic', category: 'slimming' },
    { id: '82', name: 'BODYBOX 2.0 PISTACHIO ICE CREAM', slug: 'bodybox-20-pistachio-ice-cream', url: 'https://ewaproduct.com/product/bodybox-20-pistachio-ice-cream', category: 'slimming' },
    { id: '83', name: 'BODYBOX 2.0 RASPBERRY', slug: 'bodybox-20-raspberry', url: 'https://ewaproduct.com/product/bodybox-20-raspberry', category: 'slimming' },
    { id: '84', name: 'BODYBOX CHOCOLATE & NUT', slug: 'bodybox-chocolate-nut', url: 'https://ewaproduct.com/product/bodybox-chocolate-nut', category: 'slimming' },
    { id: '85', name: 'BODYBOX VANILLA', slug: 'bodybox-vanilla', url: 'https://ewaproduct.com/product/bodybox-vanilla', category: 'slimming' },
    { id: '86', name: 'BODYBOX CAPPUCCINO', slug: 'bodybox-cappuccino', url: 'https://ewaproduct.com/product/bodybox-cappuccino', category: 'slimming' },
    { id: '87', name: 'PROTEIN DOUBLE CHOCOLATE', slug: 'protein-double', url: 'https://ewaproduct.com/product/protein-double', category: 'slimming' },
    { id: '88', name: 'PROTEIN NOUGAT', slug: 'protein-noigat', url: 'https://ewaproduct.com/product/protein-noigat', category: 'slimming' },
    { id: '89', name: 'PROTEIN MELON', slug: 'protein-melon', url: 'https://ewaproduct.com/product/protein-melon', category: 'slimming' },
    { id: '90', name: 'ZEROZEFIR PISTACHIO', slug: 'zerozefir-fistashka', url: 'https://ewaproduct.com/product/zerozefir-fistashka', category: 'slimming' },
    { id: '91', name: 'ZEROZEFIR ICE CREAM', slug: 'zerozefir-plombir', url: 'https://ewaproduct.com/product/zerozefir-plombir', category: 'slimming' },
    { id: '92', name: 'ZEROZEFIR STRAWBERRY', slug: 'zerozefir-zemlyanika', url: 'https://ewaproduct.com/product/zerozefir-zemlyanika', category: 'slimming' },
    { id: '93', name: 'PROTEIN BAR I`M SUPER', slug: 'protein-bar-im-super', url: 'https://ewaproduct.com/product/protein-bar-im-super', category: 'slimming' },
    { id: '94', name: 'PROTEIN BAR I`M STRONG', slug: 'protein-bar-im-strong', url: 'https://ewaproduct.com/product/protein-bar-im-strong', category: 'slimming' },
    { id: '95', name: 'PROTEIN BAR I`M POWER', slug: 'protein-bar-im-power', url: 'https://ewaproduct.com/product/protein-bar-im-power', category: 'slimming' },
    { id: '96', name: 'PROTEIN WAFERS I`M CHILL', slug: 'protein-wafers-im-chill', url: 'https://ewaproduct.com/product/protein-wafers-im-chill', category: 'slimming' },
    { id: '97', name: 'PROTEIN WAFERS I`M HARD', slug: 'protein-wafers-im-hard', url: 'https://ewaproduct.com/product/protein-wafers-im-hard', category: 'slimming' },
    { id: '98', name: 'PROTEIN WAFERS I`M TOP', slug: 'protein-wafers-im-top', url: 'https://ewaproduct.com/product/protein-wafers-im-top', category: 'slimming' },
    { id: '99', name: 'ICE BABY', slug: 'ice-baby', url: 'https://ewaproduct.com/product/ice-baby', category: 'slimming' },
    { id: '100', name: 'FIRE BABY', slug: 'fire-baby', url: 'https://ewaproduct.com/product/fire-baby', category: 'slimming' },
  ],
  'healthy-eating': [
    { id: '101', name: 'BODYBOX 2.0 TROPICAL MIX', slug: 'bodybox-20-pistachio-tropic', url: 'https://ewaproduct.com/product/bodybox-20-pistachio-tropic', category: 'healthy-eating' },
    { id: '102', name: 'BODYBOX 2.0 PISTACHIO ICE CREAM', slug: 'bodybox-20-pistachio-ice-cream', url: 'https://ewaproduct.com/product/bodybox-20-pistachio-ice-cream', category: 'healthy-eating' },
    { id: '103', name: 'BODYBOX 2.0 RASPBERRY', slug: 'bodybox-20-raspberry', url: 'https://ewaproduct.com/product/bodybox-20-raspberry', category: 'healthy-eating' },
    { id: '104', name: 'BODYBOX CHOCOLATE & NUT', slug: 'bodybox-chocolate-nut', url: 'https://ewaproduct.com/product/bodybox-chocolate-nut', category: 'healthy-eating' },
    { id: '105', name: 'BODYBOX VANILLA', slug: 'bodybox-vanilla', url: 'https://ewaproduct.com/product/bodybox-vanilla', category: 'healthy-eating' },
    { id: '106', name: 'BODYBOX CAPPUCCINO', slug: 'bodybox-cappuccino', url: 'https://ewaproduct.com/product/bodybox-cappuccino', category: 'healthy-eating' },
    { id: '107', name: 'PROTEIN DOUBLE CHOCOLATE', slug: 'protein-double', url: 'https://ewaproduct.com/product/protein-double', category: 'healthy-eating' },
    { id: '108', name: 'PROTEIN NOUGAT', slug: 'protein-noigat', url: 'https://ewaproduct.com/product/protein-noigat', category: 'healthy-eating' },
    { id: '109', name: 'PROTEIN MELON', slug: 'protein-melon', url: 'https://ewaproduct.com/product/protein-melon', category: 'healthy-eating' },
    { id: '110', name: 'ZEROZEFIR PISTACHIO', slug: 'zerozefir-fistashka', url: 'https://ewaproduct.com/product/zerozefir-fistashka', category: 'healthy-eating' },
    { id: '111', name: 'ZEROZEFIR ICE CREAM', slug: 'zerozefir-plombir', url: 'https://ewaproduct.com/product/zerozefir-plombir', category: 'healthy-eating' },
    { id: '112', name: 'ZEROZEFIR STRAWBERRY', slug: 'zerozefir-zemlyanika', url: 'https://ewaproduct.com/product/zerozefir-zemlyanika', category: 'healthy-eating' },
    { id: '113', name: 'PROTEIN BAR I`M SUPER', slug: 'protein-bar-im-super', url: 'https://ewaproduct.com/product/protein-bar-im-super', category: 'healthy-eating' },
    { id: '114', name: 'PROTEIN BAR I`M STRONG', slug: 'protein-bar-im-strong', url: 'https://ewaproduct.com/product/protein-bar-im-strong', category: 'healthy-eating' },
    { id: '115', name: 'PROTEIN BAR I`M POWER', slug: 'protein-bar-im-power', url: 'https://ewaproduct.com/product/protein-bar-im-power', category: 'healthy-eating' },
    { id: '116', name: 'PROTEIN WAFERS I`M CHILL', slug: 'protein-wafers-im-chill', url: 'https://ewaproduct.com/product/protein-wafers-im-chill', category: 'healthy-eating' },
    { id: '117', name: 'PROTEIN WAFERS I`M HARD', slug: 'protein-wafers-im-hard', url: 'https://ewaproduct.com/product/protein-wafers-im-hard', category: 'healthy-eating' },
    { id: '118', name: 'PROTEIN WAFERS I`M TOP', slug: 'protein-wafers-im-top', url: 'https://ewaproduct.com/product/protein-wafers-im-top', category: 'healthy-eating' },
  ],
  drinks: [
    { id: '119', name: 'EWA TEA GREEN', slug: 'ewa-tea-new', url: 'https://ewaproduct.com/product/ewa-tea-new', category: 'drinks' },
    { id: '120', name: 'EWA TEA BLACK', slug: 'tea-black-new', url: 'https://ewaproduct.com/product/tea-black-new', category: 'drinks' },
    { id: '121', name: 'EWA TEA GREEN', slug: 'ewa-tea-green', url: 'https://ewaproduct.com/product/ewa-tea-green', category: 'drinks' },
    { id: '122', name: 'EWA TEA RED', slug: 'ewa-tea-red', url: 'https://ewaproduct.com/product/ewa-tea-red', category: 'drinks' },
    { id: '123', name: 'EWA TEA BLACK', slug: 'ewa-tea-black', url: 'https://ewaproduct.com/product/ewa-tea-black', category: 'drinks' },
    { id: '124', name: 'EWA TEA MIX', slug: 'ewa-tea-mix', url: 'https://ewaproduct.com/product/ewa-tea-mix', category: 'drinks' },
  ],
  'beauty-and-care': [
    { id: '125', name: 'ANTI-AGE SET', slug: 'anti-age-box-new', url: 'https://ewaproduct.com/product/anti-age-box-new', category: 'beauty-and-care' },
    { id: '126', name: 'ANTI-AGE DAY CREAM', slug: 'anti-age-day-cream', url: 'https://ewaproduct.com/product/anti-age-day-cream', category: 'beauty-and-care' },
    { id: '127', name: 'ANTI-AGE NIGHT CREAM', slug: 'anti-age-night-cream', url: 'https://ewaproduct.com/product/anti-age-night-cream', category: 'beauty-and-care' },
    { id: '128', name: 'ANTI-AGE MULTI-SERUM', slug: 'anti-age-multi-serum', url: 'https://ewaproduct.com/product/anti-age-multi-serum', category: 'beauty-and-care' },
    { id: '129', name: 'ANTI-AGE EYE CREAM', slug: 'anti-age-eye-cream', url: 'https://ewaproduct.com/product/anti-age-eye-cream', category: 'beauty-and-care' },
    { id: '130', name: 'ANTI ACNE BOX', slug: 'nabor-anti-acne', url: 'https://ewaproduct.com/product/nabor-anti-acne', category: 'beauty-and-care' },
    { id: '131', name: 'ANTI ACNE BALANCE TONIC', slug: 'anti-acne-balance-tonic', url: 'https://ewaproduct.com/product/anti-acne-balance-tonic', category: 'beauty-and-care' },
    { id: '132', name: 'ANTI ACNE CLEANSING GEL', slug: 'anti-acne-cleansing-gel', url: 'https://ewaproduct.com/product/anti-acne-cleansing-gel', category: 'beauty-and-care' },
    { id: '133', name: 'ANTI ACNE CREAM', slug: 'anti-acne-cream', url: 'https://ewaproduct.com/product/anti-acne-cream', category: 'beauty-and-care' },
    { id: '134', name: 'ANTI ACNE SERUM', slug: 'anti-acne-serum', url: 'https://ewaproduct.com/product/anti-acne-serum', category: 'beauty-and-care' },
    { id: '135', name: 'TAN WATER', slug: 'tan-water', url: 'https://ewaproduct.com/product/tan-water', category: 'beauty-and-care' },
    { id: '136', name: 'SOLAR HARMONY', slug: 'solar-harmony', url: 'https://ewaproduct.com/product/solar-harmony', category: 'beauty-and-care' },
    { id: '137', name: 'AQUA MASK', slug: 'aqua-mask', url: 'https://ewaproduct.com/product/aqua-mask', category: 'beauty-and-care' },
    { id: '138', name: 'DETOX MASK', slug: 'detox-mask', url: 'https://ewaproduct.com/product/detox-mask', category: 'beauty-and-care' },
    { id: '139', name: 'TONIC-WATER', slug: 'tonic-water', url: 'https://ewaproduct.com/product/tonic-water', category: 'beauty-and-care' },
    { id: '140', name: 'IDEAL TONE', slug: 'ideal-tone', url: 'https://ewaproduct.com/product/ideal-tone', category: 'beauty-and-care' },
    { id: '141', name: 'AQUA TOUCH', slug: 'aqua-touch', url: 'https://ewaproduct.com/product/aqua-touch', category: 'beauty-and-care' },
    { id: '142', name: 'SUPER SKIN', slug: 'super-skin', url: 'https://ewaproduct.com/product/super-skin', category: 'beauty-and-care' },
    { id: '143', name: 'LUCKY DAY', slug: 'lucky-day', url: 'https://ewaproduct.com/product/lucky-day', category: 'beauty-and-care' },
    { id: '144', name: 'MAGNETIC EYE', slug: 'magnetic-eye', url: 'https://ewaproduct.com/product/magnetic-eye', category: 'beauty-and-care' },
    { id: '145', name: 'MIRROR PATCHES', slug: 'mirror-patches', url: 'https://ewaproduct.com/product/mirror-patches', category: 'beauty-and-care' },
    { id: '146', name: 'FOUR AMINO ACIDS WHITE', slug: 'four-amino-acids-white', url: 'https://ewaproduct.com/product/four-amino-acids-white', category: 'beauty-and-care' },
    { id: '147', name: 'BLACK CAVIAR', slug: 'black-caviar', url: 'https://ewaproduct.com/product/black-caviar', category: 'beauty-and-care' },
    { id: '148', name: 'PEELING MASK', slug: 'peeling-mask', url: 'https://ewaproduct.com/product/peeling-mask', category: 'beauty-and-care' },
    { id: '149', name: 'PERFECT MASK', slug: 'perfect-mask', url: 'https://ewaproduct.com/product/perfect-mask', category: 'beauty-and-care' },
    { id: '150', name: 'YOUNG MASK', slug: 'young-mask', url: 'https://ewaproduct.com/product/young-mask', category: 'beauty-and-care' },
    { id: '151', name: 'SMOOTH MASK', slug: 'smooth-mask', url: 'https://ewaproduct.com/product/smooth-mask', category: 'beauty-and-care' },
    { id: '152', name: 'HARD MAN\'S VIBE', slug: 'hard-mans-vibe', url: 'https://ewaproduct.com/product/hard-mans-vibe', category: 'beauty-and-care' },
    { id: '153', name: 'WILD MAN\'S VIBE', slug: 'wild-mans-vibe', url: 'https://ewaproduct.com/product/wild-mans-vibe', category: 'beauty-and-care' },
    { id: '154', name: 'SMART BALANCE', slug: 'smart-balance', url: 'https://ewaproduct.com/product/smart-balance', category: 'beauty-and-care' },
    { id: '155', name: 'SMART REPAIR', slug: 'smart-repair', url: 'https://ewaproduct.com/product/smart-repair', category: 'beauty-and-care' },
    { id: '156', name: 'SMART CONDITIONER', slug: 'smart-conditioner', url: 'https://ewaproduct.com/product/smart-conditioner', category: 'beauty-and-care' },
    { id: '157', name: 'SMART MASK', slug: 'smart-mask', url: 'https://ewaproduct.com/product/smart-mask', category: 'beauty-and-care' },
    { id: '158', name: 'SMART SPRAY', slug: 'smart-spray', url: 'https://ewaproduct.com/product/smart-spray', category: 'beauty-and-care' },
    { id: '159', name: 'LET\'S EASY', slug: 'lets-easy', url: 'https://ewaproduct.com/product/lets-easy', category: 'beauty-and-care' },
    { id: '160', name: 'LET\'S GLAM', slug: 'lets-glam', url: 'https://ewaproduct.com/product/lets-glam', category: 'beauty-and-care' },
    { id: '161', name: 'KEEP SMILE SOFT WHITENING', slug: 'keep-smile-soft-whitening', url: 'https://ewaproduct.com/product/keep-smile-soft-whitening', category: 'beauty-and-care' },
    { id: '162', name: 'KEEP SMILE TOTAL CARE', slug: 'keep-smile-total-care', url: 'https://ewaproduct.com/product/keep-smile-total-care', category: 'beauty-and-care' },
    { id: '163', name: 'KEEP SMILE BRUSH PINK', slug: 'keep-smile-pink', url: 'https://ewaproduct.com/product/keep-smile-pink', category: 'beauty-and-care' },
    { id: '164', name: 'KEEP SMILE BRUSH WHITE', slug: 'keep-smile-white', url: 'https://ewaproduct.com/product/keep-smile-white', category: 'beauty-and-care' },
    { id: '165', name: 'WASH IT СINNAMON&COOKIE', slug: 'wash-it-cinnamon-cookie', url: 'https://ewaproduct.com/product/wash-it-cinnamon-cookie', category: 'beauty-and-care' },
    { id: '166', name: 'FOOT CREAM', slug: 'foot-cream', url: 'https://ewaproduct.com/product/foot-cream', category: 'beauty-and-care' },
    { id: '167', name: 'HAND CREAM "SPICY VANILLA"', slug: 'hand-cream-spicy-vanilla', url: 'https://ewaproduct.com/product/hand-cream-spicy-vanilla', category: 'beauty-and-care' },
    { id: '168', name: 'HAND CREAM "CHARMING CHERRY"', slug: 'hand-cream-charming-cherry', url: 'https://ewaproduct.com/product/hand-cream-charming-cherry', category: 'beauty-and-care' },
    { id: '169', name: 'SLIM SCRUB «CURRANT BUSH»', slug: 'slim-scrub-brush', url: 'https://ewaproduct.com/product/slim-scrub-brush', category: 'beauty-and-care' },
    { id: '170', name: 'DETOX SCRUB «CANDY CARAMEL»', slug: 'detox-scrub-caramel', url: 'https://ewaproduct.com/product/detox-scrub-caramel', category: 'beauty-and-care' },
    { id: '171', name: 'BODY CREAM "CHARMING CHERRY"', slug: 'body-cream-charming-cherry', url: 'https://ewaproduct.com/product/body-cream-charming-cherry', category: 'beauty-and-care' },
    { id: '172', name: 'BODY CREAM "SPICY VANILLA"', slug: 'body-cream-spicy-vanilla', url: 'https://ewaproduct.com/product/body-cream-spicy-vanilla', category: 'beauty-and-care' },
    { id: '173', name: 'ICE BABY', slug: 'ice-baby', url: 'https://ewaproduct.com/product/ice-baby', category: 'beauty-and-care' },
    { id: '174', name: 'FIRE BABY', slug: 'fire-baby', url: 'https://ewaproduct.com/product/fire-baby', category: 'beauty-and-care' },
    { id: '175', name: 'HARMONY & BEAUTY', slug: 'harmony-beauty', url: 'https://ewaproduct.com/product/harmony-beauty', category: 'beauty-and-care' },
  ],
  'gift-ideas': [
    { id: '176', name: 'FOCUS ON ENERGY & RESULT', slug: 'focus-on-energy-result', url: 'https://ewaproduct.com/product/focus-on-energy-result', category: 'gift-ideas' },
    { id: '177', name: 'FOCUS ON SLIM & BEAUTY', slug: 'focus-on-slim-beauty', url: 'https://ewaproduct.com/product/focus-on-slim-beauty', category: 'gift-ideas' },
    { id: '178', name: 'FOCUS ON MIND & RELAX', slug: 'focus-on-mind-relax', url: 'https://ewaproduct.com/product/focus-on-mind-relax', category: 'gift-ideas' },
    { id: '179', name: 'STRENGTH & OPPORTUNITIES', slug: 'strength-opportunities', url: 'https://ewaproduct.com/product/strength-opportunities', category: 'gift-ideas' },
    { id: '180', name: 'POWER & ENERGY', slug: 'power-energy', url: 'https://ewaproduct.com/product/power-energy', category: 'gift-ideas' },
    { id: '181', name: 'ENERGY & SENSUAL', slug: 'energy-sensual', url: 'https://ewaproduct.com/product/energy-sensual', category: 'gift-ideas' },
    { id: '182', name: 'HARMONY & BEAUTY', slug: 'harmony-beauty', url: 'https://ewaproduct.com/product/harmony-beauty', category: 'gift-ideas' },
  ],
  home: [
    { id: '183', name: 'NAGAROFF', slug: 'nagaroff', url: 'https://ewaproduct.com/product/nagaroff', category: 'home' },
    { id: '184', name: 'ZASOROFF', slug: 'zasoroff', url: 'https://ewaproduct.com/product/zasoroff', category: 'home' },
    { id: '185', name: 'OXY REMOVE', slug: 'oxy-remove', url: 'https://ewaproduct.com/product/oxy-remove', category: 'home' },
    { id: '186', name: 'REMOVE', slug: 'remove', url: 'https://ewaproduct.com/product/remove', category: 'home' },
    { id: '187', name: 'LAUNDER', slug: 'launder', url: 'https://ewaproduct.com/product/launder', category: 'home' },
    { id: '188', name: 'SOFT', slug: 'soft', url: 'https://ewaproduct.com/product/soft', category: 'home' },
    { id: '189', name: 'CLEAN', slug: 'clean', url: 'https://ewaproduct.com/product/clean', category: 'home' },
    { id: '190', name: 'BATHE', slug: 'bathe', url: 'https://ewaproduct.com/product/bathe', category: 'home' },
    { id: '191', name: 'DISH UP', slug: 'dish-up2', url: 'https://ewaproduct.com/product/dish-up2', category: 'home' },
    { id: '192', name: 'CALM DOWN', slug: 'calm-down', url: 'https://ewaproduct.com/product/calm-down', category: 'home' },
  ],
  accessories: [
    { id: '193', name: 'Таблетница', slug: 'tabletnica-otkryl-vypil-pobediltabletnica-otkryl-vypil-pobedil', url: 'https://ewaproduct.com/product/tabletnica-otkryl-vypil-pobediltabletnica-otkryl-vypil-pobedil', category: 'accessories' },
    { id: '194', name: 'EWA BEATER', slug: 'ewa-beater', url: 'https://ewaproduct.com/product/ewa-beater', category: 'accessories' },
    { id: '195', name: 'Футболка ENERGY&POWER BLACK', slug: 'energy-power-black', url: 'https://ewaproduct.com/product/energy-power-black', category: 'accessories' },
    { id: '196', name: 'Футболка ENERGY&POWER GREEN', slug: 'energy-power-green', url: 'https://ewaproduct.com/product/energy-power-green', category: 'accessories' },
    { id: '197', name: 'Футболка ENERGY&POWER PINK', slug: 'energy-power-pink', url: 'https://ewaproduct.com/product/energy-power-pink', category: 'accessories' },
    { id: '198', name: 'Футболка', slug: 'futbolka', url: 'https://ewaproduct.com/product/futbolka', category: 'accessories' },
    { id: '199', name: 'Худи ENERGY&POWER WHITE', slug: 'energy-power-white-hudi', url: 'https://ewaproduct.com/product/energy-power-white-hudi', category: 'accessories' },
    { id: '200', name: 'Худи ENERGY&POWER BLACK', slug: 'energy-power-black-hudi', url: 'https://ewaproduct.com/product/energy-power-black-hudi', category: 'accessories' },
    { id: '201', name: 'Худи ENERGY&POWER GREEN', slug: 'energy-power-green-hudi', url: 'https://ewaproduct.com/product/energy-power-green-hudi', category: 'accessories' },
    { id: '202', name: 'Худи ENERGY&POWER PINK', slug: 'energy-power-pink-hudi', url: 'https://ewaproduct.com/product/energy-power-pink-hudi', category: 'accessories' },
    { id: '203', name: 'Шейкер life gets better', slug: 'sheyker-life-gets-better', url: 'https://ewaproduct.com/product/sheyker-life-gets-better', category: 'accessories' },
    { id: '204', name: 'Шейкер just begin', slug: 'sheyker-just-begin', url: 'https://ewaproduct.com/product/sheyker-just-begin', category: 'accessories' },
    { id: '205', name: 'Ручка', slug: 'ruchka', url: 'https://ewaproduct.com/product/ruchka', category: 'accessories' },
    { id: '206', name: 'Блокнот на кольцах с гибкой обложкой', slug: 'notebook-rings-ewa', url: 'https://ewaproduct.com/product/notebook-rings-ewa', category: 'accessories' },
    { id: '207', name: 'Блокнот', slug: 'bloknot', url: 'https://ewaproduct.com/product/bloknot', category: 'accessories' },
    { id: '208', name: 'СТИКЕРПАК EWA', slug: 'stikerpak-ewa', url: 'https://ewaproduct.com/product/stikerpak-ewa', category: 'accessories' },
    { id: '209', name: 'ПАКЕТ NEW', slug: 'paket-new', url: 'https://ewaproduct.com/product/paket-new', category: 'accessories' },
    { id: '210', name: 'ПАКЕТ ПОДАРОЧНЫЙ', slug: 'paket-podarochnyy', url: 'https://ewaproduct.com/product/paket-podarochnyy', category: 'accessories' },
    { id: '211', name: 'Пакет фирменный S', slug: 'paket-firmennyy', url: 'https://ewaproduct.com/product/paket-firmennyy', category: 'accessories' },
    { id: '212', name: 'Пакет фирменный XL', slug: 'branded-bag-xl', url: 'https://ewaproduct.com/product/branded-bag-xl', category: 'accessories' },
    { id: '213', name: 'Пакет крафтовый (большой)', slug: 'paket-kraftovyy-big', url: 'https://ewaproduct.com/product/paket-kraftovyy-big', category: 'accessories' },
    { id: '214', name: 'Пакет крафтовый (малый)', slug: 'paket-kraftovyy-malie', url: 'https://ewaproduct.com/product/paket-kraftovyy-malie', category: 'accessories' },
  ],
  'activation-kits': [
    { id: '215', name: 'BIG SLIM SET', slug: 'big-set-2-new', url: 'https://ewaproduct.com/product/big-set-2-new', category: 'activation-kits' },
    { id: '216', name: 'BESTSELLERS', slug: 'bestsellers-new', url: 'https://ewaproduct.com/product/bestsellers-new', category: 'activation-kits' },
    { id: '217', name: 'IMMUNO SET', slug: 'immuno-set-2', url: 'https://ewaproduct.com/product/immuno-set-2', category: 'activation-kits' },
    { id: '218', name: 'SLIM SET', slug: 'slim-set-new', url: 'https://ewaproduct.com/product/slim-set-new', category: 'activation-kits' },
    { id: '219', name: 'BEAUTY SET', slug: 'beauty-set-2', url: 'https://ewaproduct.com/product/beauty-set-2', category: 'activation-kits' },
  ],
  'expert-cosmetics': [
    { id: '220', name: 'ANTI-AGE SET', slug: 'anti-age-box-new', url: 'https://ewaproduct.com/product/anti-age-box-new', category: 'expert-cosmetics' },
    { id: '221', name: 'ANTI-AGE DAY CREAM', slug: 'anti-age-day-cream', url: 'https://ewaproduct.com/product/anti-age-day-cream', category: 'expert-cosmetics' },
    { id: '222', name: 'ANTI-AGE NIGHT CREAM', slug: 'anti-age-night-cream', url: 'https://ewaproduct.com/product/anti-age-night-cream', category: 'expert-cosmetics' },
    { id: '223', name: 'ANTI-AGE MULTI-SERUM', slug: 'anti-age-multi-serum', url: 'https://ewaproduct.com/product/anti-age-multi-serum', category: 'expert-cosmetics' },
    { id: '224', name: 'ANTI-AGE EYE CREAM', slug: 'anti-age-eye-cream', url: 'https://ewaproduct.com/product/anti-age-eye-cream', category: 'expert-cosmetics' },
    { id: '225', name: 'ANTI ACNE BOX', slug: 'nabor-anti-acne', url: 'https://ewaproduct.com/product/nabor-anti-acne', category: 'expert-cosmetics' },
    { id: '226', name: 'ANTI ACNE BALANCE TONIC', slug: 'anti-acne-balance-tonic', url: 'https://ewaproduct.com/product/anti-acne-balance-tonic', category: 'expert-cosmetics' },
    { id: '227', name: 'ANTI ACNE CLEANSING GEL', slug: 'anti-acne-cleansing-gel', url: 'https://ewaproduct.com/product/anti-acne-cleansing-gel', category: 'expert-cosmetics' },
    { id: '228', name: 'ANTI ACNE CREAM', slug: 'anti-acne-cream', url: 'https://ewaproduct.com/product/anti-acne-cream', category: 'expert-cosmetics' },
    { id: '229', name: 'ANTI ACNE SERUM', slug: 'anti-acne-serum', url: 'https://ewaproduct.com/product/anti-acne-serum', category: 'expert-cosmetics' },
  ],
};

// Generate all products array (combining all categories)
export const allProducts: Product[] = Object.values(products).flat();